language: python
python: 3.5
sudo: required

branches:
    only:
        - master
        - /^\d\.\d+$/

services:
    - docker

before_install:
    - docker run -d -p 8050:8050 --net=host scrapinghub/splash:master
    # Autologin
    - pip install -U pip wheel
    - pip install git+https://github.com/TeamHG-Memex/autologin.git
    - formasaurus init
    - autologin-http-api &

install:
    - pip install -U tox codecov

script: tox

after_success:
    - codecov

cache:
    directories:
        - $HOME/.cache/pip

